### ISSUE TITLE
MacOS: notarizing required for Catalina/Jan 2020

### ISSUE THREAD

**Issue by auturgy** [ArduPilot/MAVProxy#685] opened 2019-09-06 20:34 UTC
https://developer.apple.com/news/?id=09032019a
This is going to cause problems for install to MacOS come Jan 2020.

**Comment by peterbarker** [comment] 2019-09-07 04:03
On Fri, 6 Sep 2019, auturgy wrote:

> https://developer.apple.com/news/?id=09032019a
> This is going to cause problems for install to MacOS come Jan 2020.

Assuming we weren't using native code - does it affect MAVProxy?

**Comment by auturgy** [comment] 2019-09-07 04:37
Unknown, just making people aware. The Apple policy seems to target binaries, so I think interpreted code should be fine so long as the interpreter and any binary dependencies are notarised. Something to test I guess.

**Comment by monkeypants** [comment] 2019-09-07 08:47
Catalina doesn't come with a python interpreter. Maybe distributing MAVProxy to that platform will require bundling a python interpreter (and all the dependencies, libraries etc) into a package then getting the whole thing blessed with their latest ritual.

We have an Apple build server at work doing a similar sort of thing for some iOS apps (build > package > bless > distribute).

**Comment by srmainwaring** [comment] 2020-11-08 21:44
I can confirm a standard brew python installation is sufficient to run MAVProxy on macOS Catalina if you install MAVProxy from the master branch.

If you are using Python 3.9 (which is now the default in brew) you may need to install pymavlink from source as well while recent changes propagate through to the released packages (there is a patch to `pymavlink/generator/mavcrc.py` to account for array.fromstring being removed in Python 3.9).

**Comment by srmainwaring** [comment] 2023-04-25 08:54
Closing - the notarising requirement does not appear to have affected MAVProxy in versions since Catalina.

**Closed by srmainwaring** 2023-04-25 08:54 UTC
Labels: MacOS
